[package]
name = "mdoc-zk-runtime"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
core-proto = { path = "../../../core/proto", default-features = false, optional = true }
core-algebra = { path = "../../../core/algebra", optional = true }
runtime-proto = { path = "../../../runtime/proto", optional = true }
runtime-algebra = { path = "../../../runtime/algebra", optional = true }
runtime-zk = { path = "../../../runtime/zk", default-features = false, optional = true }
runtime-random = { path = "../../../runtime/random", default-features = false, optional = true }
runtime-ligero = { path = "../../../runtime/ligero", default-features = false, optional = true }
compile-compiler = { path = "../../../compile/compiler", optional = true }
compile-algebra = { path = "../../../compile/algebra", optional = true }
mdoc-zk-proto = { path = "../proto", optional = true }
mdoc-zk-compile = { path = "../compile", optional = true }
mdoc-zk-circuits = { path = "../circuits", default-features = false, optional = true }
circuits-sha256 = { path = "../../../circuits/sha256", optional = true }
circuits-bitvec = { path = "../../../circuits/bitvec", optional = true }
circuits-mac = { path = "../../../circuits/mac", optional = true }
circuits-sha256msg = { path = "../../../circuits/sha256msg", optional = true }
circuits-ec = { path = "../../../circuits/ec", optional = true }
circuits-ecdsa2 = { path = "../../../circuits/ecdsa2", optional = true }
compile-logic = { path = "../../../compile/logic", optional = true }
zstd = { version = "0.13", optional = true }
sha2 = { version = "0.10", optional = true }
mdoc-zk-artifacts = { path = "../artifacts", optional = true }

[features]
default = ["verifier"]
verifier = [
    "dep:core-proto",
    "dep:core-algebra",
    "dep:runtime-proto",
    "dep:runtime-algebra",
    "dep:runtime-zk",
    "dep:runtime-random",
    "dep:runtime-ligero",
    "dep:mdoc-zk-proto",
    "dep:mdoc-zk-circuits",
    "mdoc-zk-circuits/verifier-support",
    "dep:zstd",
    "dep:sha2",
]
prover = [
    "verifier",
    "runtime-zk/prover",
    "runtime-random/secure-random",
    "mdoc-zk-circuits/testonly",
    "dep:circuits-sha256",
    "circuits-sha256/testonly",
    "dep:circuits-bitvec",
    "circuits-bitvec/testonly",
    "dep:circuits-mac",
    "circuits-mac/testonly",
    "dep:circuits-sha256msg",
    "circuits-sha256msg/testonly",
    "dep:circuits-ec",
    "circuits-ec/testonly",
    "dep:circuits-ecdsa2",
    "circuits-ecdsa2/testonly",
]
circuit-provider = [
    "prover",
    "core-proto/legacy-lfa1",
    "dep:compile-compiler",
    "dep:compile-algebra",
    "dep:mdoc-zk-compile",
    "dep:compile-logic",
    "dep:mdoc-zk-artifacts",
]
testonly = [
    "prover",
    "circuit-provider",
    "runtime-algebra/testonly",
    "runtime-random/testonly",
    
    "compile-logic/testonly",
    "circuits-bitvec/testonly",
    "circuits-sha256/testonly",
    "circuits-sha256msg/testonly",
    "circuits-ec/testonly",
    "circuits-ecdsa2/testonly",
    "circuits-mac/testonly",
]

[dev-dependencies]
mdoc-zk-runtime = { path = "./", features = ["testonly"] }
mdoc-zk-testcases = { path = "../testcases" }
runtime-random = { path = "../../../runtime/random", features = ["testonly"] }
criterion = "0.5"
num-bigint = "0.4"

[[bench]]
name = "mdoc_zk_bench_v7"
harness = false
required-features = ["prover", "circuit-provider"]

[[bench]]
name = "mdoc_zk_bench_current"
harness = false
required-features = ["prover", "circuit-provider"]

[[bin]]
name = "convert_circuits"
path = "src/bin/convert_circuits.rs"
required-features = ["circuit-provider"]

[[test]]
name = "runtime_tests"
required-features = ["prover", "circuit-provider"]
