[package]
name = "mdoc-zk-circuits"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
compile-algebra = { path = "../../../compile/algebra", optional = true }
circuits-boolean = { path = "../../../circuits/boolean", optional = true }
circuits-bitvec = { path = "../../../circuits/bitvec", optional = true }
circuits-analog-adder = { path = "../../../circuits/analog_adder", optional = true }
circuits-routing = { path = "../../../circuits/routing", optional = true }
circuits-mac = { path = "../../../circuits/mac", optional = true }
circuits-mac-gf128 = { path = "../../../circuits/mac_gf128", optional = true }
circuits-sha256 = { path = "../../../circuits/sha256", optional = true }
circuits-sha256msg = { path = "../../../circuits/sha256msg", optional = true }
circuits-big-bitvec = { path = "../../../circuits/big_bitvec", optional = true }
circuits-ecdsa2 = { path = "../../../circuits/ecdsa2", optional = true }
circuits-memcmp = { path = "../../../circuits/memcmp", optional = true }
compile-eval = { path = "../../../compile/eval", optional = true }
compile-compiler = { path = "../../../compile/compiler", optional = true }
compile-logic = { path = "../../../compile/logic", optional = true }
num-bigint = { version = "0.4", optional = true }
sha2 = { version = "0.10", optional = true }
zeroize = { version = "1.8", features = ["derive"], optional = true }

core-algebra = { path = "../../../core/algebra", optional = true }
runtime-algebra = { path = "../../../runtime/algebra", optional = true }
mdoc-zk-testcases = { path = "../testcases", optional = true }
mdoc-zk-proto = { path = "../proto", optional = true }

[features]
default = ["circuit-compiler"]
verifier-support = ["dep:sha2", "dep:zeroize"]
circuit-compiler = [
    "verifier-support",
    "dep:compile-algebra",
    "dep:circuits-boolean",
    "dep:circuits-bitvec",
    "dep:circuits-analog-adder",
    "dep:circuits-routing",
    "dep:circuits-mac",
    "dep:circuits-mac-gf128",
    "dep:circuits-sha256",
    "dep:circuits-sha256msg",
    "dep:circuits-big-bitvec",
    "dep:circuits-ecdsa2",
    "dep:circuits-memcmp",
    "dep:compile-compiler",
    "dep:compile-logic",
    "dep:num-bigint",
    "dep:core-algebra",
    "dep:mdoc-zk-proto",
]
testonly = [
    "circuit-compiler",
    "dep:mdoc-zk-testcases",
    "dep:compile-eval",
    "dep:runtime-algebra",
    "compile-logic/testonly",
    "circuits-boolean/testonly",
    "circuits-bitvec/testonly",
    "circuits-big-bitvec/testonly",
    "circuits-sha256/testonly",
    "circuits-sha256msg/testonly",
    "circuits-ecdsa2/testonly",
    "circuits-mac/testonly",
    "circuits-mac-gf128/testonly",
    "runtime-algebra/testonly",
]

[dev-dependencies]
core-proto = { path = "../../../core/proto" }
circuits-ec = { path = "../../../circuits/ec", features = ["testonly"] }
mdoc-zk-circuits = { path = "./", features = ["testonly"] }
zstd = "0.13"
