[package]
name = "runtime-ligero"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
util = { path = "../../util" }
runtime-algebra = { path = "../algebra" }
runtime-proto = { path = "../proto" }
runtime-random = { path = "../random", default-features = false }
runtime-merkle = { path = "../merkle", default-features = false }
sha2 = "0.10.8"
core-algebra = { path = "../../core/algebra" }
zeroize = "1.8"

[features]
default = ["prover"]
prover = ["runtime-merkle/prover"]

[[test]]
name = "ligero"
required-features = ["prover"]
