[package]
name = "runtime-zk"
version = "0.2.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
runtime-algebra = { path = "../algebra" }
runtime-proto = { path = "../proto" }
runtime-random = { path = "../random", default-features = false }
runtime-sumcheck = { path = "../sumcheck", default-features = false }
runtime-ligero = { path = "../ligero", default-features = false }
core-proto = { path = "../../core/proto", default-features = false }
core-algebra = { path = "../../core/algebra" }
zeroize = "1.8"
[dev-dependencies]
runtime-random = { path = "../random", features = ["testonly"] }

[features]
default = []
prover = ["runtime-sumcheck/prover", "runtime-ligero/prover"]

[[test]]
name = "zk"
required-features = ["prover"]
